/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coladeimpresion;

import java.awt.Image;
import java.io.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author alejo
 */
public class FrmColaImpresion extends javax.swing.JFrame {
//Definir Variables a utilizar en diferentes procesos.
    Cola<String> cola = new Cola();
    String[] items = new String[4];
    Nodo<String> nodo;

    /**
     * Creates new form FrmColaImpresion
     */
    public FrmColaImpresion() {
        initComponents();
        ImageIcon imagen= new ImageIcon("src/Archivos/init.jpg");
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(),lblImagen.getHeight(),Image.SCALE_DEFAULT));
        lblImagen.setIcon(icono);
        this.repaint();
        JpImprimiendo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JpImprimiendo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jlbl = new javax.swing.JLabel();
        lblFile = new java.awt.Label();
        BtnCargarDatos = new javax.swing.JButton();
        BtnIniciarSimulacion = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        label1 = new java.awt.Label();
        lblList = new java.awt.Label();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));

        JpImprimiendo.setBackground(new java.awt.Color(255, 255, 255));
        JpImprimiendo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        JpImprimiendo.setEnabled(false);
        JpImprimiendo.setPreferredSize(new java.awt.Dimension(185, 158));
        JpImprimiendo.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Imprimiendo...");

        Jlbl.setText("Espere...");
        Jlbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblFile.setAlignment(java.awt.Label.CENTER);
        lblFile.setText("................");

        javax.swing.GroupLayout JpImprimiendoLayout = new javax.swing.GroupLayout(JpImprimiendo);
        JpImprimiendo.setLayout(JpImprimiendoLayout);
        JpImprimiendoLayout.setHorizontalGroup(
            JpImprimiendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpImprimiendoLayout.createSequentialGroup()
                .addGroup(JpImprimiendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpImprimiendoLayout.createSequentialGroup()
                        .addGroup(JpImprimiendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpImprimiendoLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1))
                            .addGroup(JpImprimiendoLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(Jlbl)))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(lblFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JpImprimiendoLayout.setVerticalGroup(
            JpImprimiendoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpImprimiendoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lblFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlbl)
                .addGap(29, 29, 29))
        );

        BtnCargarDatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnCargarDatos.setText("Cargar Datos");
        BtnCargarDatos.setPreferredSize(new java.awt.Dimension(200, 25));
        BtnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarDatosActionPerformed(evt);
            }
        });

        BtnIniciarSimulacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnIniciarSimulacion.setText("Iniciar Simulación");
        BtnIniciarSimulacion.setEnabled(false);
        BtnIniciarSimulacion.setPreferredSize(new java.awt.Dimension(200, 25));
        BtnIniciarSimulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIniciarSimulacionMouseClicked(evt);
            }
        });
        BtnIniciarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarSimulacionActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.setMargin(new java.awt.Insets(1, 14, 2, 14));
        BtnSalir.setPreferredSize(new java.awt.Dimension(200, 25));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("Simulación de una Cola de Impresión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(BtnIniciarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblList, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JpImprimiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JpImprimiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblList, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIniciarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 //
    public static String getString(String archivo) {

        String cadena = "";
        FileReader file = null;
        try {
            file = new FileReader(archivo);
            BufferedReader br = new BufferedReader(file);
            try {
                cadena = br.readLine();
                br.close();
                file.close();

            } catch (IOException ex) {
                System.out.println("Error de lectura de archivo");
            }
        } catch (FileNotFoundException e) {
            System.out.println("No se ha encontrado el archivo");
        }
        return cadena;
    }
 //Boton Salir
    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed
//Boton Cargar Datos (Archivo .txt a utilizar)
    private void BtnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarDatosActionPerformed
      String cadena = getString("src/Archivos/spool.txt");
        System.out.println("spool.text = " + cadena);
        items = cadena.split(";");
        updateCola();
        System.out.println(" ===== Tamaño de la cola: " + cola.getSize() + " =====");
        
        
        BtnIniciarSimulacion.setEnabled(true);
        BtnCargarDatos.setEnabled(false);
    }//GEN-LAST:event_BtnCargarDatosActionPerformed
//Actualizar Cola (metodo indexof paar encontrar el texto o número)
    private void updateCola() {
        String str = "";
        for (int i = 0; i < items.length; i++) {
//          System.out.print((i + 1) + ". " + items[i].substring(0, items[i].indexOf(",")) + " = " + items[i].substring(items[i].indexOf(",") + 1) + "\n");
            cola.enqueue((i + 1) + ". " + items[i].substring(0, items[i].indexOf(",")));
            str += ((i + 1) + ". " + items[i].substring(0, items[i].indexOf(",")) + "<br><br>");
        }
       
        cola.display();
        System.out.println("coladeimpresion.FrmColaImpresion.updateCola()");
 

//  javax.swing.JOptionPane.showMessageDialog(null, "<html><p style='color:blue;'>Hola Es<br>Stackoverflow</p></html>"); //mensaje simple
        
    }
    
    //Boton Inicira Simulación (

    private void BtnIniciarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarSimulacionActionPerformed
 
        for (String item : items) {
            nodo = cola.dequeue();
            lblFile.setText(nodo.getValor());
//            System.out.println("bandera");
//                System.out.println(nodo.getValor());
            System.out.println("|------------------------------------|");
            esperar(Integer.parseInt(item.substring(item.indexOf(",") + 1)));
            System.out.println("------------------------------------");
            //tiempo de espera de 10 minutos despues de cada proceso
            JpImprimiendo.setVisible(false);
            esperar(5);
            JpImprimiendo.setVisible(true);
            System.out.println("|------------------------------------|");
        }
        lblFile.setText("No hay archivos en cola");
        BtnIniciarSimulacion.setEnabled(false);
        System.out.println(" ===== Tamño de la cola: " + cola.getSize() + " =====");
        esperar(2);
        lblFile.setText("................");
        BtnCargarDatos.setEnabled(true);
        
    }//GEN-LAST:event_BtnIniciarSimulacionActionPerformed
// Esperar despues de tanto tiempo para que se vuelva al proceso 
    public void esperar(int segundos) {
        try {
            Thread.sleep(segundos * 1000);
            System.out.println(" Tiempo del proceso: " + segundos);
        } catch (InterruptedException e) {
            // Mensaje en caso de que falle
        }
    }
    
    private void BtnIniciarSimulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIniciarSimulacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIniciarSimulacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new FrmColaImpresion().setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargarDatos;
    private javax.swing.JButton BtnIniciarSimulacion;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel Jlbl;
    private javax.swing.JPanel JpImprimiendo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label lblFile;
    private javax.swing.JLabel lblImagen;
    private java.awt.Label lblList;
    // End of variables declaration//GEN-END:variables
}
